const theme = {
    "default": {
        layout: "default-font show",
        navDrawer: "default-font",
        navigation: "default-font",
        link: "default-font",
        appBar: "default-font",
        field: "default-font",
        label: "default-font",
        dialog: "default-font",
        error: "default-font",
        errored: "default-font",
        input: "default-font",
        inputElement: "default-font",
        bar: "default-font",
        button: "default-font",
        snackbar: "default-font",
        pinned: "default-font", // pinned sidebar
        emailLoginActive: "true"
    },
    "wollok": {
        layout: "wollok-layout",
        navDrawer: "wollok-navDrawer",
        vertical: "wollok-navigation-vertical",
        link: "wollok-link",
        appBar: "wollok-appbar",
        leftIcon: "wollok-lefticon", // appBar leftIcon
        menu: "wollok-menu",
        menuItem: "wollok-menuitem",
        caption: "wollok-caption",
        panel: "wollok-panel",
        field: "wollok-field",
        on: "wollok-switch-on",
        off: "wollok-switch-off",
        thumb: "wollok-switch-thumb",
        text: "wollok-text",
        check: "wollok-check",
        checked: "wollok-checked",
        label: "wollok-label",
        overlay: "wollok-overlay",
        dialog: "wollok-dialog",
        error: "wollok-error",
        errored: "wollok-errored",
        input: "wollok-input",
        inputElement: "wollok-inputElement",
        disabled: "wollok-disabled",
        autocomplete: "wollok-autocomplete",
        suggestions: "wollok-suggestions",
        suggestion: "wollok-suggestion",
        active: "wollok-active",
        dropdown: "wollok-dropdown",
        value: "wollok-value",
        values: "wollok-values",
        selected: "wollok-selected",
        focus: "wollok-focus",
        hint: "wollok-hint",
        bar: "wollok-bar",
        button: "wollok-button",
        primary: "wollok-primary",
        cancel: "wollok-cancel",
        rippleWrapper: "wollok-rippleWrapper",
        ripple: "wollok-ripple",
        icon: "wollok-icon",
        snackbar: "wollok-snackbar",
        pinned: "wollok-pinned", // pinned sidebar
        emailLoginActive: "false"
    },
    "wollok-login": {
        layout: "wollok-layout",
        navDrawer: "wollok-font",
        navigation: "wollok-font",
        link: "wollok-font",
        appBar: "wollok-font",
        field: "wollok-font",
        label: "wollok-login-label",
        overlay: "wollok-login-overlay",
        dialog: "wollok-login-dialog",
        error: "wollok-login-input-error",
        errored: "wollok-login-input-errored",
        input: "wollok-login-input",
        inputElement: "wollok-login-inputElement",
        bar: "wollok-login-bar",
        button: "wollok-login-button",
        icon: "wollok-login-icon",
        rippleWrapper: "wollok-login-rippleWrapper",
        ripple: "wollok-login-ripple",
        snackbar: "wollok-login-snackbar",
        pinned: "wollok-font", // pinned sidebar
        emailLoginActive: "false"
    },
    "seatDesigner": {
        slider: "seat-slider",
        knob: "seat-knob",
        innerknob: "seat-innerknob",
        ring: "seat-ring"
    }
};

export default theme;